### ISSUE TITLE
Where to copy the pages folder and issue with different lgon URL  Account/Login or Identity/Account/Login

### ISSUE THREAD

**Issue by riaadh** [DuendeSoftware/IdentityServer.Quickstart.UI.AspNetIdentity#4]
Hello, 
I am starting with the identity server with EF template, the default login page is Identity/Account/Login 

  builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
            .AddEntityFrameworkStores<ApplicationDbContext>();

I am trying to add the ui page to customize the identity pages; 
i changed the code 
       builder.Services.AddIdentity<ApplicationUser, IdentityRole>()
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddDefaultTokenProviders();

now the default login page is Account/Login and not working even when i add the pages folder.

What i am missing?

Thank you

**Comment by brockallen** [comment]
You can set the options telling IdentityServer where your pages are:

https://docs.duendesoftware.com/identityserver/v6/reference/options/#userinteraction

For example: 

```
services.AddIdentityServer(options =>
{
    options.LoginUrl = "/Identity/Account/Login";
});
```
